### ISSUE TITLE
Invalid argument type for 'convert_timezone' 

### ISSUE THREAD

**Issue by 1zaak** [calogica/dbt-date#76] opened 2022-07-28 09:48 UTC
Trying to convert a UTC to a timezone. Received this error even using this example in the docs:
`{{ dbt_date.convert_timezone("created_at", "America/New_York", "UTC") }}   `

The error:
`Invalid argument types for function 'CONVERT_TIMEZONE': (VARCHAR(3), VARCHAR(16), TIMESTAMP_TZ(9))`

**Comment by clausherther** [comment] 2022-07-28 13:26
@1zaak what platform are you on?.

**Comment by 1zaak** [comment] 2022-07-28 14:04
> @1zaak what platform are you on?.
Macbook local environment. Snowflake warehouse.

**Comment by clausherther** [comment] 2022-07-28 14:21
mmh on my Snowflake instance, I'm calling this
```sql
dbt_date.convert_timezone('time_stamp_utc', 'America/Los_Angeles', 'UTC')
```
which dbt-date generates as:

```sql
select
    time_stamp_utc,
    cast(convert_timezone('UTC', 'America/Los_Angeles', time_stamp_utc) as timestamp_ntz)
from 
    analytics.dbt_date_integration_tests.test_dates 
```
and this runs fine?

**Comment by clausherther** [comment] 2022-07-28 14:24
Interesting, looks like the 3 argument version does not work with `timestamp_tz`
```
CONVERT_TIMEZONE( <source_tz> , <target_tz> , <source_timestamp_ntz> )
```
https://docs.snowflake.com/en/sql-reference/functions/convert_timezone.html

but the 2 argument version does (works with any timestamp).

In our integration test data we cast our test timestamp using `dbt_utils.type_timestamp()` which returns a `timestamp_ntz`. You may have to do the same thing or use the 2 argument version (I think that should work).

**Comment by clausherther** [comment] 2022-07-28 14:26
I'll make a note to update the `convert_timezone` macro to include a Snowflake specific version that does the cast for the 3 argument version.

**Comment by clausherther** [comment] 2022-07-29 01:17
@1zaak I think the problem is that your column is a timestamp_tz, not timestamp_ntz and Snowflake no longer accepts that as in put the the conver_timezone function with 3 params. We use all 3 params by default even if you don't specify a source timezone.
I'd try this, i.e. convert your column to a timestamp_ntz first:

```sql
{{ dbt_date.convert_timezone("cast(created_at as " ~ dbt_utils.type_timestamp() ~ ")", "America/New_York") }}

```

**Comment by 1zaak** [comment] 2022-07-29 01:20
Nice that works. I tried casting it but didn't get the syntax right. Thanks @clausherther

**Comment by clausherther** [comment] 2022-07-29 01:21
@1zaak glad that worked. Timezones are a giant pain, but thankfully dbt-labs is working on moving this into dbt-core, hopefully soon!
See: https://github.com/dbt-labs/dbt-core/issues/5521

**Closed** 2022-07-29 01:20 UTC
Labels: bug
